### ISSUE TITLE
Project specification file structure revision 1

### ISSUE THREAD

**Issue by farhoud** [assister-ai/upm#2]
package is a folder with a `upm.yml` in its root. the upm.yml inspired by `package.json` and include project specification:
- name: (string) name of project
- author: (string) name of main authors
- description: (string) short summary of project
- version: (string) version of package 
- dependencies: (array of string) name of upm dependency packages
- entrypoints: (map) list of executable that your package publish:
  - name: (string) name or alias for your execution
    - command: (string) executable command 
    - ports: (map)(optional) list of port maps
      - internal port: port in package internal network
      - external port: port map in host
```yaml
name: foo
author: foo
description: foo bar
version: 0.0.1
dependencies:
 - python
 - node
entrypoints:
  run:
    command: node index.js
    ports:
      3000: 3000
  server_up:
    command: python server.py
    ports:
      5000: 5000
```
missing functionality:
- library dependencies like pip or cpp headers

**Comment by farhoud** [comment]
port mapping structure is not final but functionality is needed.

**Comment by farhoud** [comment]
as far as we done in proto-type every entry-point will have a container in workspace , do we need to know which on is daemon?

**Comment by farhoud** [comment]
how to express ports that does not need to expose to outside network?

**Comment by mehdibalouchi** [comment]
docker itself recommends not to run more than one process in a container.
in the current architecture (proto-type) upm creates a container for each command execution so there would be no problem, BUT if we are going to have `UPMd` for command execution, things will be different.
`UPMd` will execute all commands on a single container, this way if a command runs a service on container every future command will cause a parallel process run on the container. seems that this architecture with `UPMd` needs to know which command will lead to a service run and which won't.

**Comment by mehdibalouchi** [comment]
in `UPMd` we can check if a container is running a service, if so, `UPMd` should create another container and execute commands on that. this must be checked every time a command is being executed. so in worst case we will have one container for each service and a single container for other commands.

**Comment by farhoud** [comment]
we can handle library dependencies like pip or cpp headers with life-cycle hooks and because every entry-point is a container, life-cycle most be part of entrypoints.

**Comment by farhoud** [comment]
> docker itself recommends not to run more than one process in a container.
> in the current architecture (proto-type) upm creates a container for each command execution so there would be no problem, BUT if we are going to have UPMd for command execution, things will be different.
> UPMd will execute all commands on a single container, this way if a command runs a service on container every future command will cause a parallel process run on the container. seems that this architecture with UPMd needs to know which command will lead to a service run and which won't.



> in UPMd we can check if a container is running a service, if so, UPMd should create another container and execute commands on that. this must be checked every time a command is being executed. so in worst case we will have one container for each service and a single container for other commands.

i agree how to express it in `upm.yml`?

**Comment by mehdibalouchi** [comment]
> i agree how to express it in upm.yml?

We don't need to express this in `upm.yml`. @farhoud could you explain it with a use case?

**Comment by farhoud** [comment]
> We don't need to express this in upm.yml. @farhoud could you explain it with a use case?

@mehdibalouchi when we run command that is daemon we can add option like `--restart-always` and  we should not create new container for it , but when the command is not daemon we can create container on execution and remove it afterward.

**Comment by mehdibalouchi** [comment]
> when we run command that is daemon we can add option like --restart-always

I think putting this in `upm.yml` might be good.
we can use a syntax like this for example:
```yml
entrypoints:
  run:
    command: node index.js
    ports:
      3000: 3000
    restart: always
  server_up:
    command: python server.py
    ports:
      5000: 5000
```
`restart: always` does the thing like `--restart-always`, this is like `docker-compose` syntax.

**Comment by mehdibalouchi** [comment]
> we can handle library dependencies like pip or cpp headers with life-cycle hooks and because every entry-point is a container, life-cycle most be part of entrypoints.

I agree with you about assuming life-cycle hooks as parts of an entrypoint, but how user will define it?
writing directly in `upm.yml` file is possible but not recommended, so we should handle this with `upm-cli` commands.

for example `pip install flask` is a command that is expected to be run before `python server.py`. so we can imagine a `upm.yml` like this:
```yml
entrypoints:
  run:
    command: node index.js
    ports:
      3000: 3000
    restart: always
    before:
      - command: pip install flask
```
user can add this block to `upm.yml` by running this command: 
`upx hooks add before run pip install flask` (or something like this)

**Comment by farhoud** [comment]
in upm-proto we use host network and everything is accessible by localhost its cool in development enviroment but i don't think its the best way and maybe we get in to trouble for deployment of the package so i suggest some kind of naming convention for every entrypoint in network like compose.
any idea?

**Comment by mehdibalouchi** [comment]
> i suggest some kind of naming convention for every entrypoint in network like compose.

👍 
@farhoud what is compose convention for this?

**Comment by farhoud** [comment]
> I agree with you about assuming life-cycle hooks as parts of an entrypoint, but how user will define it?
> writing directly in upm.yml file is possible but not recommended, so we should handle this with upm-cli commands.
> 
> for example pip install flask is a command that is expected to be run before python server.py. so we can imagine a upm.yml like this:
> 
> entrypoints:
>   run:
>     command: node index.js
>     ports:
>       3000: 3000
>     restart: always
>     before:
>       - command: pip install flask
> 
> user can add this block to upm.yml by running this command:
> upx hooks add before run pip install flask (or something like this)
:+1: 
we need to know base distribution and its package manager of dependency base image to work with it how to handle it?

**Comment by farhoud** [comment]
in compose 

> @farhoud what is compose convention for this?
docker container in docker network use container's name as domain and docker handles dns.
container name convention in compose is :
folder_name + service_name + [number from zero]
and there is container_name option that let you change it

**Comment by mehdibalouchi** [comment]
> we need to know base distribution and its package manager of dependency base image to work with it how to handle it?

docker engine finds this out somehow, can we request docker daemon for this information? if not I guess we can implement a similar feature to that of docker engine

**Comment by farhoud** [comment]
> docker engine finds this out somehow, can we request docker daemon for this information? if not I guess we can implement a similar feature to that of docker engine

i cant find any think yet, but it must be possible base on sha256 of base layer we can determine what is distro and version, another way is to run the image and check its distro.

**Comment by farhoud** [comment]
> in upm-proto we use host network and everything is accessible by localhost its cool in development enviroment but i don't think its the best way and maybe we get in to trouble for deployment of the package so i suggest some kind of naming convention for every entrypoint in network like compose.

we need to think about how to handle clusters.

**Comment by farhoud** [comment]
one thing we forget is `Dockerfile | docker image` compatibility, at the upm-proto the Dockerfile was in root of the yml tree :
```yaml
author: farhoud
docker: ./Dockerfile
description: testing new featers
entrypoints:
  node:
    command: node
  npm:
    command: npm
name: node
version: 0.0.1
```
but i think it most be part of entrypoints, but the entrypoints is getting more and more like compose
and i not feeling good about it!

**Comment by farhoud** [comment]
after several meetings with @mehdibalouchi and @keyvan-m-sadeghi we conclude :
- first of all, library dependencies should be installed via `Dockerfile`.
- every upm package is single container so as its dependencies.(they may not agree but its my call)
- base can be Docker image or `Dockerfile` or UPM package and for this i add these keywords to root of `upm.yml`:
  - build: [Dockerfile]
  - image: [docker image]
  - upm: [UPM package]
- we introduce tag called alias for duplicated entrypoints.
- another add tag to root is service which will define network connection between dependencies and express container writable layer (Docker CMD) :
  - ```yaml
    author: farhoud
    build: ./Dockerfile
    description: testing new featers
    service:
         before: [command]
         on: [command]
         ports:
           [external]: [internal_port]
- upm.yml structure:
  - ```yaml
    author: farhoud
    build: ./Dockerfile
    description: testing new featers
    entrypoints:
      [alias]: [command]
      node:  node
    name: node
    version: 0.0.1

**Comment by farhoud** [comment]
I think we have good progress, one last thing is needed mount mechanism and roles:
in brief we have mount dependencies files in universal_modules/[package_name]
there is two stories:
1. source convention which is let user to put his source code inside folder source near `upm.yml` and upm handle mounting
2. docker ported project which need for mountings definitions : 
 I like to add this under service called volumes that will be an array of mount map:
  - ```yaml
    service:
      volumes:
        - [folder_name]: [container_path]

folder_name: 
  universal_modules/[package_name]/[folder_name]
